### ISSUE TITLE
May i give a advise for the orm interface what expected for adding a method of native query str like ...

### ISSUE THREAD

**Issue by fizzcome** [CraryPrimitiveMan/create-your-own-php-framework#4]
May i give a advise for the orm interface what expected for adding a method of native query str like '$Model->query(select filed1,filed2 from $table where id=? and name=?, $id, $name)' etc. It can be also using for '$Model->query(update/delete/insert...)' .

**Comment by harrysun-code** [comment]
@fizzcome 
I'd like use the orm like the following code

``` php
Model::find()->select(['id', 'name'])->where(['id' => 1])->orderBy(['createdAt' => SORT_DESC])->all();
Model::find()->where(['id' => 1])->one();
```

But now I just want to simplify the find method.
Maybe I will follow the example in the future.

**Comment by fizzcome** [comment]
yeah. it will be hard for the query builder like join,left join and so on ...

**Comment by harrysun-code** [comment]
Yeah, it's hard. But I think we can try.
